### model
model_name_or_path: /workspace/huangxiaoniu/diffu/llama-3.2-1B
print_param_status: true
tokenizer_name: /workspace/huangxiaoniu/diffu/llama-3.2-1B
add_bos_token: false
trust_remote_code: true        


### method
stage: ddm-sft
do_train: true
finetuning_type: lora
lora_target: all
additional_target: embed_tokens
lora_rank: 16

### dataset
dataset: /path/to/slimpajama  
template: empty
cutoff_len: 2048 
streaming: false
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output/llama3.2-1b-ddm
logging_steps: 10
save_steps: 2000
save_total_limit: 4
plot_loss: false
overwrite_output_dir: true

### train
per_device_train_batch_size: 4  
gradient_accumulation_steps: 4  
learning_rate:  1.5e-4   
num_train_epochs: 3  
lr_scheduler_type: cosine
warmup_steps: 1000  
bf16: true
ddp_timeout: 180000000
anneal_steps: 10000  
shift: true
remove_unused_columns: false

### eval
val_size: 256
per_device_eval_batch_size: 4 
eval_strategy: steps
eval_steps: 200
